apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    certmanager.k8s.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "notifier.fullname" . }}-serving-cert
  creationTimestamp: null
  name: {{ include "notifier.fullname" . }}-validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "notifier.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}      
      path: /validate-notifying-containers-ai-v1alpha1-alamedanotificationchannel
  failurePolicy: Fail
  name: valamedanotificationchannel.containers.ai
  rules:
  - apiGroups:
    - notifying.containers.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alamedanotificationchannels
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "notifier.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}      
      path: /validate-notifying-containers-ai-v1alpha1-alamedanotificationtopic
  failurePolicy: Fail
  name: valamedanotificationtopic.containers.ai
  rules:
  - apiGroups:
    - notifying.containers.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alamedanotificationtopics
