{{- if .Values.global.predictQueueEnable }}
apiVersion: apps/v1
kind: Deployment 
metadata:  
  namespace: {{ .Release.Namespace }}  
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "rabbitmq.name" . }}
      release: "{{ .Release.Name }}"  
  template:
    metadata:
      labels:
        app: {{ template "rabbitmq.name" . }}
        release: "{{ .Release.Name }}"
        chart: {{ template "rabbitmq.chart" .  }}
      {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
      {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.global.rbacEnable }}
      serviceAccountName: {{ template "rabbitmq.fullname" . }}
      {{- end }}      
      terminationGracePeriodSeconds: 10
      containers:        
      - name: rabbitmq
        image: {{ template "rabbitmq.image" . }}       
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "status"]           
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}          
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}                  
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]              
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}          
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }} 
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: "{{ .Values.rabbitmq.username }}"            
          - name: RABBITMQ_DEFAULT_PASS
            value: "{{ .Values.rabbitmq.password }}"
{{- end }}
