---
apiVersion: v1
kind: Service
metadata:
  name: admission-controller
  namespace: alameda
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: admission-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-controller
  namespace: alameda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alameda:admission-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - replicationcontrollers
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
      - list
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alameda:admission-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda:admission-controller
subjects:
  - kind: ServiceAccount
    name: admission-controller
    namespace: alameda
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: admission-controller
  namespace: alameda
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: admission-controller
    spec:
      serviceAccountName: admission-controller
      containers:
        - image: admission-controller:latest
          imagePullPolicy: Always
          name: admission-controller
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 200Mi
          env:
            - name: ALAMEDA_ADMCTL_ENABLE
              value: "false"
          ports:
            - containerPort: 443
          volumeMounts:
            - name: tls-certs
              mountPath: "/etc/tls-certs"
              readOnly: true
      serviceAccount: admission-controller
      volumes:
        - name: tls-certs
          secret:
            secretName: admission-controller-tls-certs
