{{- if .Values.global.predictQueueEnable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aidispatcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: alameda
    component: {{ .Values.global.component.aidispatcher.name }}
spec:
  replicas: {{ .Values.global.component.aidispatcher.replicaCount }}
  selector:
    matchLabels:
      app: alameda
      component: {{ .Values.global.component.aidispatcher.name }}
  template:
    metadata:
      labels:
        app: alameda
        component: {{ .Values.global.component.aidispatcher.name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ALAMEDA_AI_DISPATCHER_DATAHUB_ADDRESS  
              value: "{{ .Values.global.component.datahub.name }}.{{ .Release.Namespace }}:{{ .Values.global.component.datahub.service.port }}"
            - name: ALAMEDA_AI_DISPATCHER_QUEUE_URL
              value: "amqp://{{ .Values.global.component.aidispatcher.rabbitmqConfig.username }}:{{ .Values.global.component.aidispatcher.rabbitmqConfig.password }}@{{ .Values.global.component.aidispatcher.rabbitmqConfig.name }}.{{ .Release.Namespace }}:{{ .Values.global.component.aidispatcher.rabbitmqConfig.port }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            exec:
              command:
              - /usr/local/bin/ai-dispatcher                
              - probe
              - --type=readiness
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/ai-dispatcher                
              - probe
              - --type=liveness
            initialDelaySeconds: 5
            periodSeconds: 5
    {{- if .Values.image.accessToken }}
      imagePullSecrets:
        - name: {{ include "aidispatcher.fullname" . }}-imagepull
    {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
