apiVersion: v1
kind: Service
metadata:
  name: {{ include "alameda-ai.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "alameda-ai.name" . }}
    helm.sh/chart: {{ include "alameda-ai.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.global.component.alamedaai.service.type }}
  ports:
    - port: {{ .Values.global.component.alamedaai.service.port }}
      protocol: TCP
      name: {{ .Values.global.component.alamedaai.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "alameda-ai.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
