version: 2
jobs:
  build_operator:
    docker:
      - image: circleci/golang:1.11.2
    working_directory: /go/src/github.com/containers-ai/alameda
    steps:
      - checkout            
      - run: cd /go/src/github.com/containers-ai/alameda/operator; make manager
  build_datahub:
    docker:
      - image: circleci/golang:1.11.2
    working_directory: /go/src/github.com/containers-ai/alameda
    steps:
      - checkout            
      - run: cd /go/src/github.com/containers-ai/alameda/datahub; make datahub
  install_kubebuilder:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - run: curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v1.0.5/kubebuilder_1.0.5_linux_amd64.tar.gz
      - run: tar -zxf kubebuilder_1.0.5_linux_amd64.tar.gz 
      - run: mv kubebuilder_1.0.5_linux_amd64 kubebuilder && sudo mv kubebuilder /usr/local/
      - persist_to_workspace:
          root: /usr/local
          paths:
            - kubebuilder/bin
  test_operator:
    docker:
      - image: circleci/golang:1.11.2
        user: root
    working_directory: /go/src/github.com/containers-ai/alameda
    environment:
      KUBEBUILDER_DIR: /usr/local/kubebuilder
      KUBEBUILDER_DIR_WORKSPACE: /tmp/workspace/kubebuilder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: if [ ! -d "$KUBEBUILDER_DIR" ];then mkdir -p $KUBEBUILDER_DIR;fi;cp -r $KUBEBUILDER_DIR_WORKSPACE/bin $KUBEBUILDER_DIR/bin
      - run: echo 'export PATH=$KUBEBUILDER_DIR/bin:$PATH' >> ~/.bashrc 
      - checkout 
      - run: cd /go/src/github.com/containers-ai/alameda/operator;make test      
      - run:
          command: |
            bash <(curl -s https://codecov.io/bash)
  test_datahub:
    docker:
      - image: circleci/golang:1.11.2
        user: root
    working_directory: /go/src/github.com/containers-ai/alameda
    steps:
      - checkout 
      - run: cd /go/src/github.com/containers-ai/alameda/datahub;make test      
      - run:
          command: |
            bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build_test:
    jobs:
      - build_operator
      - build_datahub
      - install_kubebuilder
      - test_operator:
          requires:
            - install_kubebuilder
      - test_datahub