version: 2
jobs:
  build:
    docker:      
      - image: circleci/golang:1.11.2
    working_directory: /go/src/github.com/containers-ai/alameda
    steps:
      - checkout            
      - run: go build -o ./operator/bin/manager github.com/containers-ai/alameda/operator/cmd/manager
