version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    working_directory: /go/src/github.com/containers-ai/alameda
    steps:
      - checkout
      - run: cd operator; make manager
workflows:
  version: 2
  build:
    jobs:
      - build
