---
apiVersion: v1
kind: Namespace
metadata:
  name: alameda
---
apiVersion: v1
kind: Service
metadata:
  name: operator
  namespace: alameda
  labels:
    app: operator
spec:
  selector:
    app: operator
  ports:
  - port: 50050
    name: grpc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: alameda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: alameda-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers
  - alamedarecommendations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# Permission for query prometheus under namespace openshift-monitoring 
- apiGroups: 
  - ""
  resources: 
  - namespaces
  verbs: 
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: alameda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-operator-role
subjects:
- kind: ServiceAccount
  name: operator
  namespace: alameda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: operator
  name: operator
  namespace: alameda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: operator
        deploymentconfig: operator
    spec:
      containers:
      - image: operator:latest
        imagePullPolicy: IfNotPresent
        name: operator
        env:
        - name: ALAMEDA_GRPC_PROMETHEUS_BEARER_TOKEN_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: ALAMEDA_AI_SERVER_ADDRESS
          value: alameda-ai.alameda:50051
        - name: ALAMEDA_GRPC_PROMETHEUS_URL
          value: http://prometheus.monitoring:9090
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: operator
      serviceAccountName: operator
      terminationGracePeriodSeconds: 30
