apiVersion: 1

deleteDatasources:
  - name: prometheus
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
- name: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: https://prometheus-k8s.openshift-monitoring.svc:9091
  basicAuth: true
  basicAuthUser: internal
  basicAuthPassword: internal
  withCredentials: false
  isDefault: false
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     tlsSkipVerify: true
  version: 1
  editable: true
