retrySec = 3

[prometheus]
namespace = "nks-system"
name = "prometheus"
configCMName = "prometheus-config"
cmConfigKey = "prometheus.yaml"

[log]
setLogcallers = true
outputLevel = "info" # debug, info, warn, error, fatal, none
filePath = "/var/log/alameda/alameda-job.log"