apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: alamedascalers.autoscaling.containers.ai
spec:
  group: autoscaling.containers.ai
  names:
    kind: AlamedaScaler
    plural: alamedascalers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            enable:
              type: boolean
            policy:
              type: string
            selector:
              type: object
          required:
          - selector
          - enable
          type: object
        status:
          properties:
            alamedaController:
              properties:
                deploymentconfigs:
                  type: object
                deployments:
                  type: object
              required:
              - deployments
              - deploymentconfigs
              type: object
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
