apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedaresources
  - alamedaresourcepredictions
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# Permission for query prometheus under namespace openshift-monitoring 
- apiGroups: 
  - ""
  resources: 
  - namespaces
  verbs: 
  - get