apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alameda-datapipe
  namespace: federatorai
spec:
  selector:
    matchLabels:
      app: alameda-datapipe
  replicas: 1
  template:
    metadata:
      labels:
        app: alameda-datapipe
    spec:
      containers:
      - name: alameda-datapipe
        image: datapipe:v0.0.1
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: alameda-datapipe
  namespace: federatorai
spec:
  ports:
  - port: 50060
    protocol: TCP
  selector:
    app: alameda-datapipe
