apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "executor.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.yml: |-
    datahub:
      address: "{{ .Values.global.component.datahub.name }}.{{ .Release.Namespace }}.svc"
      port: {{ .Values.global.component.datahub.service.port }}
    executor:
      check-cycle: 3   # second
      expire-time: 300 # second
      enable: true