apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: alameda-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers
  - alamedarecommendations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedascalers/finalizers
  verbs:
  - update
# Permission for query prometheus under namespace openshift-monitoring 
- apiGroups: 
  - ""
  resources: 
  - namespaces
  verbs: 
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alameda-datahub-role
rules:
# Permission for query prometheus under namespace openshift-monitoring 
- apiGroups: 
  - ""
  resources: 
  - namespaces
  verbs: 
  - get
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedarecommendations
  verbs:
  - get
  - update
