---
# Source: grafana/templates/clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: grafana
    chart: grafana-2.0.1
    release: alameda-grafana
    heritage: Tiller
  name: alameda-grafana-clusterrole
rules: []
