---
# Source: grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: alameda-grafana
  labels:
    app: grafana
    chart: grafana-2.0.1
    heritage: Tiller
    release: alameda-grafana
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [alameda-grafana]
