---
# Source: grafana/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: alameda-grafana
  namespace: alameda
  labels:
    app: grafana
    chart: grafana-3.5.7
    release: alameda-grafana
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "YWRtaW4="
  ldap-toml: ""
