---
# Source: grafana/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-2.0.1
    heritage: Tiller
    release: alameda-grafana
  name: alameda-grafana
