---
apiVersion: autoscaling.containers.ai/v1alpha1
kind: AlamedaResource
metadata:
  name: alameda
  namespace: webapp
spec:
  policy: compact
  enable: true
  selector:
    matchLabels:
      app: nginx
