apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: operator
  name: operator
  namespace: alameda
spec:
  replicas: 1
  selector:
    app: operator
    deploymentconfig: operator
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: operator
        deploymentconfig: operator
    spec:
      containers:
      - env:
        - name: ALAMEDA_OPERATOR_GRPC_PROMETHEUS_BEARER_TOKEN_FILE
          value: /var/run/secrets/kubernetes.io/serviceaccount/token
        - name: ALAMEDA_OPERATOR_GRPC_PROMETHEUS_HOST
          value: prometheus24.kube-system.svc.cluster.local
        - name: ALAMEDA_OPERATOR_GRPC_PROMETHEUS_PORT
          value: "80"
        - name: ALAMEDA_OPERATOR_GRPC_PROMETHEUS_PROTOCOL
          value: http
        imagePullPolicy: Always
        name: operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: operator
      serviceAccountName: operator
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - operator
      from:
        kind: ImageStreamTag
        name: operator:latest
        namespace: alameda
    type: ImageChange
